name: Linter
description: Linter

on:
  push:
    branches:
      - master
    paths:
      - 'storefront/**/*'

runs:
  using: composite
  steps:
    - name: Run Linter
      uses: github/super-linter@v3.17.0
      env: 
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ inputs.token }}