name: Linter
description: Linter
secrets:
  github_token:
    description: Github token to use github libs
    required: true

jobs:
  lint: 
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: github/super-linter@v3.17.0
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.github_token }}