name: Linter
description: Linter

inputs:
  token:
    description: Github token to use github libs
    required: true

runs:
  using: composite
  steps:
    - name: Run Linter
      uses: github/super-linter@v3.17.0
      env: 
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ inputs.token }}