name: Linter
description: Linter

inputs:
    github_token:
        description: Github token to use github libs
        required: true

jobs:
  intermediate:
    outputs:
      environment: ${{ inputs.github_token }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  lint: 
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: github/super-linter@v3.17.0
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ inputs.github_token }}