name: Linter
description: Linter

jobs:
  lint: 
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: github/super-linter@v3.17.0
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}