name: Invalidate cache
description: Invalidating cache process

inputs:
    keys:
        description: Keys of cache to delete
        required: true
    github_token:
        description: Github secrets
        required: true

runs:
    using: composite
    steps:
#        - uses: actions/github-script@v6
        - name: Clear
          shell: bash
          run: |
              set -e  
              IFS=',' read -ra keys <<< "${{ keys }}"
              for key in "${keys[@]}"
              do
                echo $key
              done
              