name: Invalidate cache
description: Invalidating cache process

inputs:
    keys:
        description: Keys of cache to delete
        required: true
    github_token:
        description: Github secrets
        required: true

runs:
    using: composite
    steps:
#        - uses: actions/github-script@v6
        - name: Clear
          shell: bash
          run: |
              set -e  
              IFS=',' read -ra keys <<< "${{ inputs.keys }}"
              for key in "${keys[@]}"
              do
                curl -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ inputs.github_token }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/actions/caches?key=$key
              done
              