name: Deploy to production

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: production
      with_code_style_check:
        type: boolean
        required: false
        default: false

jobs:
  # Ввиду противного бага https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111
  # Я вынужден делать так
  intermediate:
    outputs:
      environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  
  #code style check (lint)
  linter:
    if: env.IS_BUILD_NEEDED == 'true'
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Linter
        uses: ./.github/actions/linter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  # Определяем будем ли запускать linter в следующий раз
  linter_launch_determinant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Determine modified files
        uses: ./.github/actions/linter_launch_determinant
      - uses: actions/cache@v3
        id: cache_legacy_assets
        env:
          LA_CACHE_PATH: ./storefront/build
          LA_CACHE_KEY: artifact-${{ hashFiles('./storefront/**') }}
        with:
          path: ${{ env.LA_CACHE_PATH }}
          key: ${{ env.LA_CACHE_KEY }}

  # DEPLOY
  codedeoploy:
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    name: Deploy to environment
    environment: ${{ inputs.environment }}
    outputs:
      environment: "Deploy finished"
      run: echo "::set-env name=IS_LINTER_NEEDED::false"
    needs:
      [
        intermediate,
        linter,
      ]
    steps:
      - run: exit 0
