name: Deploy
on:
  workflow_dispatch:
    inputs:
      deployFront:
        description: 'Deploy frontend'
        type: boolean
        required: false
        default: false
      deployBack:
        description: 'Deploy backend'
        type: boolean
        required: false
        default: false
jobs:
  build-frontend:
    if: ${{ github.event.inputs.deployFront == 'true'}}
    permissions:
      contents: read
      id-token: write
    name: "Build frontend"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: "Imitations of build frontend"
        run: echo "Frontend builded"

  build-backend:
    if: ${{ github.event.inputs.deployBack == 'true'}}
    permissions:
      contents: read
      id-token: write
    name: "Build backend"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: "Imitations of build backend"
        run: echo "Backend builded"

  pre-deploy:
    if: ${{ always() }}
    needs: [ build-frontend, build-backend ]
    runs-on: ubuntu-latest
    name: "Pre deploy checking"
    
  deploy:
    needs: [ pre-deploy ]
    if: (needs.pre-deploy.result == 'success')
    runs-on: ubuntu-latest  
    name: "Deploy"
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: "Imitations of deploy"
        run: echo "Deploy finished"