name: Linter

on: 
  push:
    branches: ["master"]

jobs:
  lint: 
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Run Linter
        uses: github/super-linter@v3
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}